/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pertemuan_15;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo IP 330-14IKB
 */
public class Ubah extends javax.swing.JFrame {

    private final LoginDAO dao = new LoginDAO();
    private Login_1 currentUser = null;

    /**
     * Creates new form Ubah
     */
    public Ubah() {
        initComponents();
        tf_Pertanyaan_Ubah.setText("");
        tf_Jawaban_Ubah.setText("");
        tf_UbahPassword.setText("");
        tf_Pertanyaan_Ubah.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_CariUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_Pertanyaan_Ubah = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_Jawaban_Ubah = new javax.swing.JTextField();
        tf_UbahPassword = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_Cari = new javax.swing.JButton();
        btn_Ubah = new javax.swing.JButton();
        lbl_Back_Ubah = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setText("UBAH PASSWORD");

        jLabel2.setText("Cari Username");

        jLabel3.setText("Pertanyaan Pengaman");

        jLabel4.setText("Jawaban Pertanyaan Pengaman");

        jLabel5.setText("Ubah Password");

        btn_Cari.setText("Cari");
        btn_Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CariActionPerformed(evt);
            }
        });

        btn_Ubah.setText("Ubah");
        btn_Ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UbahActionPerformed(evt);
            }
        });

        lbl_Back_Ubah.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_Back_Ubah.setText("<");
        lbl_Back_Ubah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_Back_UbahMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_Ubah)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(tf_CariUsername)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(tf_Pertanyaan_Ubah)
                                .addComponent(tf_Jawaban_Ubah)
                                .addComponent(jLabel5)
                                .addComponent(tf_UbahPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Cari))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_Back_Ubah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Back_Ubah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_CariUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Cari))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_Pertanyaan_Ubah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_Jawaban_Ubah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_UbahPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btn_Ubah)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CariActionPerformed
        // TODO add your handling code here:
        String username = tf_CariUsername.getText().trim();
        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan username untuk mencari", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        try {
            Login_1 user = dao.findByUsername(username);
            if (user == null) {
                JOptionPane.showMessageDialog(this, "Username tidak ditemukan", "Error", JOptionPane.ERROR_MESSAGE);
                tf_Pertanyaan_Ubah.setText("");
                tf_Pertanyaan_Ubah.setEditable(false);
                currentUser = null;
                return;
            }

            currentUser = user;
            tf_Pertanyaan_Ubah.setText(user.getPertanyaan() != null ? user.getPertanyaan() : "");
            tf_Pertanyaan_Ubah.setEditable(true);

            JOptionPane.showMessageDialog(this, "User ditemukan. Silakan jawab pertanyaan pengaman.", "Info", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat pencarian: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btn_CariActionPerformed

    private void btn_UbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UbahActionPerformed
        // TODO add your handling code here:
        if (currentUser == null) {
            JOptionPane.showMessageDialog(this, "Cari username terlebih dahulu.", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        String jawabanInput = tf_Jawaban_Ubah.getText().trim();
        if (jawabanInput.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Isi jawaban pertanyaan pengaman.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String storedJawaban = currentUser.getJawaban() != null ? currentUser.getJawaban() : "";
        if (!jawabanInput.equals(storedJawaban)) {
            JOptionPane.showMessageDialog(this, "Jawaban pengaman salah.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String newPw = tf_UbahPassword.getText().trim();
        if (newPw.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan password baru.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String oldPw = currentUser.getPw() != null ? currentUser.getPw() : "";
        if (newPw.equals(oldPw)) {
            JOptionPane.showMessageDialog(this, "Password baru harus berbeda dari password lama.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String newPertanyaan = tf_Pertanyaan_Ubah.getText().trim();
        String newJawaban = tf_Jawaban_Ubah.getText().trim();

        try {
            boolean ok = dao.updatePassword(currentUser.getUsername(), newPw, newPertanyaan, newJawaban);
            if (ok) {
                JOptionPane.showMessageDialog(this, "Password berhasil diperbarui. Silakan login dengan password baru.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                // kembali ke Login
                Login login = new Login();
                login.setLocationRelativeTo(this);
                login.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal memperbarui password.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat update: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_UbahActionPerformed

    private void lbl_Back_UbahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_Back_UbahMouseClicked
        // TODO add your handling code here:
        try {
            Login login = new Login();
            login.setLocationRelativeTo(this);
            login.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Gagal kembali: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_lbl_Back_UbahMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ubah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ubah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ubah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ubah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ubah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cari;
    private javax.swing.JButton btn_Ubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private java.awt.Label lbl_Back_Ubah;
    private javax.swing.JTextField tf_CariUsername;
    private javax.swing.JTextField tf_Jawaban_Ubah;
    private javax.swing.JTextField tf_Pertanyaan_Ubah;
    private javax.swing.JTextField tf_UbahPassword;
    // End of variables declaration//GEN-END:variables
}
